# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nonhashpass.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(351, 426)
        mainWindow.setMinimumSize(QtCore.QSize(351, 426))
        mainWindow.setMaximumSize(QtCore.QSize(351, 426))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 130, 311, 25))
        self.lineEdit.setStyleSheet("selection-background-color: rgb(24, 24, 24);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 210, 311, 25))
        self.lineEdit_2.setStyleSheet("selection-background-color: rgb(24, 24, 24);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 290, 311, 25))
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_3.setStyleSheet("selection-background-color: rgb(24, 24, 24);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 251, 41))
        self.label.setStyleSheet("font: 100 11pt \"Waree\"; alignment: center;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 151, 21))
        self.label_2.setStyleSheet("font: 11pt \"Waree\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 91, 21))
        self.label_3.setStyleSheet("font: 11pt \"Waree\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 171, 21))
        self.label_4.setStyleSheet("font: 11pt \"Waree\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 260, 121, 21))
        self.label_6.setStyleSheet("font: 11pt \"Waree\";")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 370, 311, 25))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(24, 24, 24);\n"
"background-color: rgb(17, 16, 16);")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 340, 171, 21))
        self.label_5.setStyleSheet("font: 11pt \"Waree\";")
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 370, 311, 21))
        self.progressBar.setStyleSheet("selection-background-color: rgb(17, 16, 16);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 340, 171, 21))
        self.label_7.setStyleSheet("font: 11pt \"Waree\";")
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 370, 311, 25))
        self.lineEdit_4.setStyleSheet("selection-background-color: rgb(24, 24, 24);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 340, 171, 20))
        self.label_8.setStyleSheet("font: 11pt \"Waree\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 260, 121, 20))
        self.label_9.setStyleSheet("font: 11pt \"Waree\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(210, 180, 121, 20))
        self.label_10.setStyleSheet("font: 11pt \"Waree\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(210, 100, 121, 20))
        self.label_11.setStyleSheet("font: 11pt \"Waree\";")
        self.label_11.setObjectName("label_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 340, 161, 25))
        self.pushButton_2.setStyleSheet("background-color: rgb(17, 16, 16);\n"
"border-top-color: rgb(238, 238, 236);\n"
"color: rgb(238, 238, 236);\n"
"selection-background-color: rgb(24, 24, 24);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 340, 161, 25))
        self.pushButton_3.setStyleSheet("background-color: rgb(17, 16, 16);\n"
"border-top-color: rgb(238, 238, 236);\n"
"color: rgb(238, 238, 236);\n"
"selection-background-color: rgb(24, 24, 24);")
        self.pushButton_3.setObjectName("pushButton_3")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "NonHashpass"))
        self.label.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">NonHashpass</span></p></body></html>"))
        self.label_2.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Password (Passphrase)</span></p></body></html>"))
        self.label_3.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Unique Word</span></p></body></html>"))
        self.label_4.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Iterations Count (Number)</span></p></body></html>"))
        self.label_6.setText(_translate("mainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; color:#a40000;\">(!) Isn\'t a number</span></p></body></html>"))
        self.pushButton.setText(_translate("mainWindow", "Make Password!"))
        self.label_5.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Generate Password</span></p></body></html>"))
        self.label_7.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">In process...</span></p></body></html>"))
        self.label_8.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Resulted Password</span></p></body></html>"))
        self.label_9.setText(_translate("mainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; color:#a40000;\">(!) Can\'t be empty</span></p></body></html>"))
        self.label_10.setText(_translate("mainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; color:#a40000;\">(!) Can\'t be empty</span></p></body></html>"))
        self.label_11.setText(_translate("mainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; color:#a40000;\">(!) Can\'t be empty</span></p></body></html>"))
        self.pushButton_2.setToolTip(_translate("mainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("mainWindow", "Generate another"))
        self.pushButton_3.setToolTip(_translate("mainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("mainWindow", "Stop"))
